<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import the tModLoader properties and build targets generated for ModSources. -->
	<Import Project="..\tModLoader.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
		
	</ItemGroup>

</Project>
