<Project Sdk="Microsoft.NET.Sdk">

	<!-- Import tModLoader mod properties via WorkspaceInfo for tModLoaderSteamPath, then tMLMod.targets for DLL references -->
	<Import Project="..\tModLoader\src\WorkspaceInfo.targets" />
	<Import Project="$(tModLoaderSteamPath)\tMLMod.targets" />

	<!-- General -->
	<PropertyGroup>
		
	</PropertyGroup>

	<!-- References -->
	<ItemGroup>
		
	</ItemGroup>

</Project>